### ISSUE TITLE
Memory Leak on EmojiPicker

### ISSUE THREAD

**Issue by fikricanc** [Finalet/Elegant-Emoji-Picker#17]
Hi,

First of all, thank you for creating this! 

However, I have noticed a memory leak when using the library. EmojiPicker never gets released from memory.

You can reproduce this issue on Demo app.

Steps to reproduce:

1. Present the emoji picker.
2. Monitor the memory usage of the app.
3. Dismiss the emoji picker.
4. Monitor the memory usage of the app again.

<img width="423" alt="image" src="https://user-images.githubusercontent.com/7072359/236672462-136a7df3-73c7-45df-b5d1-7f2c78499a1a.png">

Thanks in advance!

**Comment by Finalet** [comment]
Hi!

Thank you for providing this. Its an annoying booboo that I'll dive deeper after my other projects. Hope its not game breaking for your app.

**Comment by fikricanc** [comment]
Thanks for responding! I'll try take a look at the source code and see if I can help identify the issue too. It's worth noting that I've also noticed similar memory leak problems in other emoji picker libraries.

I'll keep you updated on my findings.

Thanks again for your help!

**Comment by Finalet** [comment]
Thanks, any help is appreciated!

**Comment by loongman** [comment]
I'd like to contribute. However, this is not doable for now, due to lack of permission.

To fix it, apply 'weak' to delegate property to avoid from reference cycle.

Could you please apply this small change to the main branch? Thanks. @Finalet 

On ElegantEmojiPicker.swift

`public var delegate: ElegantEmojiPickerDelegate?`
->
`public weak var delegate: ElegantEmojiPickerDelegate?`

And on ElegantEmojiPickerDelegate.swift

`public protocol ElegantEmojiPickerDelegate`
-> 
`public protocol ElegantEmojiPickerDelegate: AnyObject`

**Comment by Finalet** [comment]
Thanks for the input, I will look into it!

In terms of contributing:

> However, this is not doable for now, due to lack of permission.

Are you unable to fork and create a pull request to the base repository? @loongman

**Comment by loongman** [comment]
As suggested, I have created a [PR](https://github.com/Finalet/Elegant-Emoji-Picker/pull/19) for this issue. @Finalet

**Comment by loongman** [comment]
The original issue should be fixed now.

However, found another quite interesting issue.

As you can see on the screen recording, after switch among different categories on the toolbar, memory increased rapidly, it stay there even after closed the picker.

After some quick investigations, it seems the OS generated huge cache(1000+ Malloc Blocks) for `label.text = emoji.emoji` on `EmojiCell.swift`. If simply replace that code line as `label.text = "A"`, then, that behavior(1000+ Malloc Blocks) is no longer observable.

Any thoughts/suggestions on that? @Finalet 

https://github.com/Finalet/Elegant-Emoji-Picker/assets/2167359/09adcb3c-f547-4b3c-b3fc-1c681f707c09

<img width="1322" alt="Screenshot 2023-06-03 at 21 46 30" src="https://github.com/Finalet/Elegant-Emoji-Picker/assets/2167359/95b27fdd-2df1-427b-8f71-be9290889d9e">
<img width="1785" alt="Screenshot 2023-06-03 at 21 47 24" src="https://github.com/Finalet/Elegant-Emoji-Picker/assets/2167359/2f8014ab-2c9a-48e5-9c98-505a57917b47">

**Comment by zizicici** [comment]
Have you tried switching the app to the background? I found that it seems to reduce memory usage to a reasonable level.

**Comment by loongman** [comment]
Good finding. @zizicici 

Memory usage can also be reduced if apply 'Debug -> Simulate Memory Warning' to Simulator.

**Comment by Amzd** [comment]
The memory leak still occurs due to `sheetPresentationController?.prefersGrabberVisible = true` 

See 
- https://developer.apple.com/forums/thread/747525 
- https://github.com/michaelhenry/prefersGrabberVisible-causing-view-controller-to-retain
- https://github.com/bdotdub/SheetPresentationGrabberLeak
- https://stackoverflow.com/questions/76839031/why-uisheetpresentationcontroller-prefersgrabbervisible-cause-variable-class-do

All with no resolution and since it's a bug in UIKit there is no way to fix it. I have tried to disable the grabber right before dismissing to fix the leak but with no luck. If the grabber was ever visible, the leak happens. I suggest turning off the grabber. If you want you can create your own grabber but users nowadays know what bottom sheets are so it's not that big a deal to not have it.

**Comment by Finalet** [comment]
@Amzd ~~I don't think we are affected by `prefersGrabberVisible`. At least, I am unable to reproduce it on my end. The view controller gets deallocated properly, even with `prefersGrabberVisible = true`. Refer to the video below: there is always only one (or zero) instance of the presented view controller.~~

Apparently, it's only a problem on a real device with iOS 16, while my simulators work fine.

https://github.com/user-attachments/assets/e4f1ba2f-a0c3-4036-868e-1a8ba898eead

**Comment by Finalet** [comment]
I do, however, acknowledge the memory leak happening from rendering emojis and scrolling through categories, as @loongman showed in his screencast.

I just battled this in my custom iOS keyboard and have researched this thoroughly. For some reason, iOS does not deallocate memory that was used in rendering an emoji as a string inside `UILabel`. Even converting the emoji string to `UIImage` to use inside `UIImageView` does not help.

The only solution I came up with for my keyboard is pre-compiling a large png atlas of all emojis. Then, plugging the respective cropped emoji into `UIImageView`. In this case, we only have to load the png atlas in memory (or break into multiple atlases and load dynamically) and reuse it for all emojis.

In my keyboard I was able to cut down RAM usage 2-3x with this approach and kill the leak. That said, its very crude, requires a built-time script to render the atlas, and is not scalable.

I suspect, for a dedicated standalone app (such as my apps where I use this library), the increased RAM usage is not too big of a deal. So, for now I'm waiting for Apple to fix their memory deallocation, unless you guys have better ideas I have missed.
